"""Publish chapters back into the game (a data file the AddOn loads on /reload) and as HTML story pages."""
from __future__ import annotations

import html
import json
import shutil
from datetime import datetime
from pathlib import Path
from typing import Any

from .archive import Archive, atomic_write_bytes, is_trivial, load_json
from .export import clock, describe, duration, export_filename, long_date, render_markdown, render_recap
from .nights import chapter_number as night_number, nights
from .paths import Paths

MAX_CHAPTERS_IN_GAME = 12
MAX_LOG_CHARS = 8000


def journal_sidecar_path(exports_dir: Path, session_id: str) -> Path:
    return exports_dir / "journal" / f"{session_id}.json"


def load_journal(exports_dir: Path, session_id: str) -> dict[str, Any] | None:
    p = journal_sidecar_path(exports_dir, session_id)
    if p.exists():
        try:
            return load_json(p)
        except (OSError, ValueError):
            return None
    return None


def chapter_title(session: dict[str, Any], journal: dict[str, Any] | None, number: int) -> str:
    if journal and journal.get("title"):
        return journal["title"]
    zones = session.get("zones", [])
    where = zones[-1].get("subzone") or zones[-1].get("zone") if zones else None
    return f"Chapter {number}" + (f" — {where}" if where else "")


def lua_string(text: str) -> str:
    text = (text or "").replace("\\", "\\\\").replace('"', '\\"').replace("\r", "").replace("\n", "\\n")
    text = text.replace("|", "||")  # keep UI escape sequences literal in FontStrings/EditBoxes
    return '"' + text + '"'


def build_chapters(archive: Archive, exports_dir: Path) -> list[dict[str, Any]]:
    chapters = []
    for session in nights(archive)[-MAX_CHAPTERS_IN_GAME:]:
        number = night_number(archive, session)
        journal = load_journal(exports_dir, session["id"])
        chapters.append({
            "id": session["id"],
            "number": number,
            "character": session["character"].get("displayName"),
            "slug": session["character"].get("slug"),
            "date": long_date(session.get("startedAt")),
            "startedAt": session.get("startedAt") or 0,
            "duration": duration(session.get("playedSeconds")),
            "title": chapter_title(session, journal, number),
            "recap": (journal or {}).get("recap") or render_recap(session),
            "journal": (journal or {}).get("journal") or "",
            "log": render_markdown(session)[:MAX_LOG_CHARS],
        })
    return chapters


def write_chapters_lua(chapters: list[dict[str, Any]], addon_src: Path) -> Path:
    lines = ["-- Generated by `ramble publish`. Do not edit; it is rewritten after every chapter.",
             "-- Loaded by WoW like any addon file, so it survives the Forever SavedVariables bug.",
             "RambleonChapters = {"]
    for c in chapters:
        lines.append("  {")
        for key in ("id", "character", "slug", "date", "duration", "title", "recap", "journal", "log"):
            lines.append(f"    {key} = {lua_string(str(c.get(key) or ''))},")
        lines.append(f"    number = {int(c.get('number') or 0)},")
        lines.append(f"    startedAt = {int(c.get('startedAt') or 0)},")
        lines.append("  },")
    lines.append("}")
    path = addon_src / "Chapters.lua"
    atomic_write_bytes(path, ("\n".join(lines) + "\n").encode("utf-8"))
    return path


def publish_chapters(archive: Archive, paths: Paths) -> tuple[Path, int]:
    chapters = build_chapters(archive, paths.exports_dir)
    return write_chapters_lua(chapters, paths.addon_src), len(chapters)


# ---------------------------------------------------------------------------------------------------
# HTML story page (for Substack, notes, or just reading in a browser)

CSS = """
body{max-width:720px;margin:40px auto;padding:0 20px;font:17px/1.6 Georgia,'Times New Roman',serif;color:#2b1d0e;background:#f5ecd8}
h1{font-size:34px;margin:0 0 4px;letter-spacing:.5px}h2{font-size:22px;margin:36px 0 8px;border-bottom:1px solid #c9b48a;padding-bottom:4px}
.meta{color:#6b5233;margin-bottom:24px}.recap{white-space:pre-line;background:#efe3c6;border-left:4px solid #b08d4c;padding:12px 16px;margin:20px 0}
.journal p{margin:0 0 14px}ul{padding-left:22px}li{margin:3px 0}figure{margin:24px 0}figure img{width:100%;border:1px solid #c9b48a;border-radius:4px}
figcaption{font-size:14px;color:#6b5233;margin-top:6px}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:8px 16px;margin:12px 0}
.stat b{display:block;font-size:24px}.stat span{font-size:13px;color:#6b5233;text-transform:uppercase;letter-spacing:1px}
footer{margin-top:48px;font-size:13px;color:#8a7250}
"""


def _paragraphs(text: str) -> str:
    out = []
    for block in [b.strip() for b in text.replace("\r", "").split("\n\n") if b.strip()]:
        if block.startswith("#"):
            continue
        out.append("<p>" + html.escape(block).replace("\n", "<br>") + "</p>")
    return "\n".join(out)


def render_html(session: dict[str, Any], journal: dict[str, Any] | None, number: int, image_dir: Path | None) -> str:
    c = session.get("character", {})
    cnt = session.get("counters", {})
    title = chapter_title(session, journal, number)
    name = c.get("displayName", "Unknown")
    parts = [f"<!doctype html><html><head><meta charset='utf-8'><title>{html.escape(title)} — {html.escape(name)}</title>",
             f"<style>{CSS}</style></head><body>",
             f"<h1>{html.escape(title)}</h1>",
             f"<div class='meta'>{html.escape(name)} · {html.escape(long_date(session.get('startedAt')))} · {html.escape(duration(session.get('playedSeconds')))} in Azeroth</div>"]
    if journal and journal.get("journal"):
        parts.append("<div class='journal'>" + _paragraphs(journal["journal"]) + "</div>")
    recap = (journal or {}).get("recap") or render_recap(session)
    parts.append("<div class='recap'>" + html.escape(recap.strip()) + "</div>")
    stats = [("Quests", cnt.get("questsCompleted", 0)), ("Places", len(session.get("zones", []))),
             ("Enemies slain", cnt.get("kills", 0)), ("Loot", cnt.get("loot", 0)), ("Deaths", cnt.get("deaths", 0)),
             ("People", len(session.get("people", []))), ("XP", f"{cnt.get('xpGained', 0):,}")]
    parts.append("<div class='stats'>" + "".join(f"<div class='stat'><b>{html.escape(str(v))}</b><span>{html.escape(k)}</span></div>" for k, v in stats) + "</div>")
    shots = session.get("screenshots", [])
    if shots:
        parts.append("<h2>Screenshots</h2>")
        events = session.get("events", [])
        for s in shots:
            src = s.get("archived") or s.get("path")
            if image_dir is not None and src and Path(src).exists():
                dest = image_dir / Path(src).name
                image_dir.mkdir(parents=True, exist_ok=True)
                if not dest.exists():
                    shutil.copy2(src, dest)
                src = f"{image_dir.name}/{dest.name}"
            cap = clock(s.get("takenAt"))
            idx = s.get("nearestEventIndex")
            if idx is not None and idx < len(events):
                cap += " — near: " + describe(events[idx])
            parts.append(f"<figure><img src='{html.escape(str(src))}' alt=''><figcaption>{html.escape(cap)}</figcaption></figure>")
    parts.append("<h2>The Journey</h2><ul>")
    for ev in session.get("events", []):
        if ev.get("type") == "RESUMED":
            continue
        parts.append(f"<li>{html.escape(clock(ev.get('t')))} — {html.escape(describe(ev))}</li>")
    parts.append("</ul>")
    notes = [ev for ev in session.get("events", []) if ev.get("type") == "NOTE"]
    if notes:
        parts.append("<h2>Notes</h2><ul>" + "".join(f"<li>{html.escape(str(ev.get('text')))}</li>" for ev in notes) + "</ul>")
    parts.append(f"<footer>Recorded by Rambleon · session {html.escape(session.get('id', ''))}</footer></body></html>")
    return "\n".join(parts)


def export_html(session: dict[str, Any], archive: Archive, exports_dir: Path) -> Path:
    number = night_number(archive, session) if session.get("kind") == "night" else archive.chapter_number(session)
    journal = load_journal(exports_dir, session["id"])
    out = exports_dir / "html" / export_filename(session).replace(".md", ".html")
    image_dir = out.with_suffix("")  # exports/html/<date>-<slug>/  next to the page
    atomic_write_bytes(out, render_html(session, journal, number, image_dir).encode("utf-8"))
    return out
